name: Build Release Artifacts
on:
  release:
    types: [created]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: 'jdk+fx'

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash

      - name: Package Java Image
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: ./gradlew packageImage

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/logfx-${{ steps.get_version.outputs.VERSION }}.zip
          asset_name: logfx-${{ steps.get_version.outputs.VERSION }}-linux.zip
          asset_content_type: application/zip
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: 'jdk+fx'

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash

      - name: Package Java Image
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: ./gradlew packageImage

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/logfx-${{ steps.get_version.outputs.VERSION }}.zip
          asset_name: logfx-${{ steps.get_version.outputs.VERSION }}-mac.zip
          asset_content_type: application/zip
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: 'jdk+fx'

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash

      - name: Package Java Image
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: ./gradlew packageImage

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/logfx-${{ steps.get_version.outputs.VERSION }}.zip
          asset_name: logfx-${{ steps.get_version.outputs.VERSION }}-windows.zip
          asset_content_type: application/zip
