name: Java CI with Gradle

on:
  push:
    branches: [ master, next ]
  pull_request:
    branches: [ master, next ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: Linux
            jb_platform: linux
          - os: macos-latest
            label: MacOS
            jb_platform: macos-arm64
          - os: windows-latest
            label: Windows
            jb_platform: windows
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '25'
          java-package: 'jdk+fx'

      - name: Download jb
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'renatoathaydes/jb'
          version: 'tags/0.16.0'
          file: 'jb-0.16.0-${{ matrix.jb_platform }}.tar.gz'
          target: jb.tar.gz

      - name: Install jb
        run: |
              mkdir jb
              tar xzf jb.tar.gz -C jb
        shell: bash

      - name: Build with jb
        run: jb/bin/jb -d

      - name: Run tests
        run: jb/bin/jb -d -p src/test compile test || true

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: 'src/test/build/test-reports/TEST-*.xml'
          check_name: 'Test Report (${{ matrix.label }})'
